[build]
  # The directory with the built HTML
  publish = "/"

# Set custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self'; script-src 'self'; style-src 'self'; font-src 'self';"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# For SPA-style redirects (if needed later)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200